fix bug NoMethodError: undefined method `upcase' for nil:NilClass
Tested with example: Romanian::Localities::County.get name: "Covasna"
On line 36 we should check if prefix is blank instead of state.. Added & for safety reasons.